-- fix - corect emote drowning watchmen 36440

DELETE FROM `creature_addon` WHERE `guid`=801712;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801712, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801714;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801714, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801716;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801716, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801718;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801718, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801719;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801719, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801721;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801721, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801722;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801722, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801723;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801723, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801726;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801726, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801727;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801727, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801729;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801729, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801731;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801731, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801733;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801733, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801734;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801734, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801735;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801735, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801736;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801736, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801738;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801738, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801739;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801739, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801742;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801742, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801743;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801743, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801744;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801744, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801745;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801745, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801746;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801746, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801748;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801748, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801749;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801749, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801750;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801750, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801751;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801751, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801752;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801752, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801753;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801753, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801754;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801754, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801755;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801755, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801757;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801757, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801758;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801758, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801759;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801759, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801761;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801761, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801763;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801763, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801764;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801764, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801765;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801765, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801766;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801766, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801767;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801767, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801768;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801768, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801769;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801769, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801770;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801770, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801771;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801771, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801897;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801897, 0, 0, 0, 1, 383, 0, 0, 0, '');
DELETE FROM `creature_addon` WHERE `guid`=801898;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `auras`) VALUES (801898, 0, 0, 0, 1, 383, 0, 0, 0, '');

-- fix - make drowning watchman cariable

DELETE FROM `npc_spellclick_spells` WHERE `npc_entry`=36440 AND `spell_id`=68735;
INSERT INTO `npc_spellclick_spells` (`npc_entry`, `spell_id`, `cast_flags`, `user_type`) 
VALUES (36440, 68735, 3, 0);
