UPDATE `gossip_menu_option` SET `OptionText` = 'auction' WHERE `MenuId` = 2352 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'bank' WHERE `MenuId` = 2352 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Horned beast administrator' WHERE `MenuId` = 2352 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Guild registrar and guild merchant' WHERE `MenuId` = 2352 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Hotel' WHERE `MenuId` = 2352 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'mailbox' WHERE `MenuId` = 2352 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'Beast manager' WHERE `MenuId` = 2352 AND `OptionIndex` = 6;
UPDATE `gossip_menu_option` SET `OptionText` = 'Battlefield officer' WHERE `MenuId` = 2352 AND `OptionIndex` = 7;
UPDATE `gossip_menu_option` SET `OptionText` = 'Vocational trainer' WHERE `MenuId` = 2352 AND `OptionIndex` = 8;
UPDATE `gossip_menu_option` SET `OptionText` = 'Professional trainer' WHERE `MenuId` = 2352 AND `OptionIndex` = 9;
UPDATE `gossip_menu_option` SET `OptionText` = 'Other continents' WHERE `MenuId` = 2352 AND `OptionIndex` = 10;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 4351 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready. Take me to the order hall.。' WHERE `MenuId` = 8750 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Take me to find other death swearers, Orum.' WHERE `MenuId` = 8750 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Well, I want to go back to the bottom of the temple.' WHERE `MenuId` = 9457 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to go to the middle of the Temple of Dragon Sleeping and talk to Commander Afrashastaz.' WHERE `MenuId` = 9457 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to tell you the mysterious redemption code and get the handle of Tyrrell.' WHERE `MenuId` = 9768 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am here to learn cooking.' WHERE `MenuId` = 9772 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to see the goods you are selling.' WHERE `MenuId` = 10180 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to see the goods you are selling.' WHERE `MenuId` = 10181 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I would like to check my deposit box.' WHERE `MenuId` = 10667 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see your goods.' WHERE `MenuId` = 10667 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 11615 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to check the items in the auction.' WHERE `MenuId` = 12941 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Come out, it’s safe now.' WHERE `MenuId` = 13814 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Come out, it’s safe now.' WHERE `MenuId` = 13815 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We are ready to defend!' WHERE `MenuId` = 13887 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Enter the trial site.' WHERE `MenuId` = 14103 AND `OptionIndex` = 8;
UPDATE `gossip_menu_option` SET `OptionText` = 'Enter the trial site.' WHERE `MenuId` = 14258 AND `OptionIndex` = 8;
UPDATE `gossip_menu_option` SET `OptionText` = 'Combat pet trainer' WHERE `MenuId` = 16042 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Illusion' WHERE `MenuId` = 16042 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Void warehouse' WHERE `MenuId` = 16042 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'auction' WHERE `MenuId` = 16042 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'bank' WHERE `MenuId` = 16042 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'barber' WHERE `MenuId` = 16042 AND `OptionIndex` = 6;
UPDATE `gossip_menu_option` SET `OptionText` = 'Battlefield officer' WHERE `MenuId` = 16042 AND `OptionIndex` = 7;
UPDATE `gossip_menu_option` SET `OptionText` = 'Vocational trainer' WHERE `MenuId` = 16042 AND `OptionIndex` = 8;
UPDATE `gossip_menu_option` SET `OptionText` = 'Wyvern controller' WHERE `MenuId` = 16042 AND `OptionIndex` = 9;
UPDATE `gossip_menu_option` SET `OptionText` = 'Guild registrar and guild merchant' WHERE `MenuId` = 16042 AND `OptionIndex` = 10;
UPDATE `gossip_menu_option` SET `OptionText` = 'Hotel' WHERE `MenuId` = 16042 AND `OptionIndex` = 11;
UPDATE `gossip_menu_option` SET `OptionText` = 'Officer\'s lounge' WHERE `MenuId` = 16042 AND `OptionIndex` = 12;
UPDATE `gossip_menu_option` SET `OptionText` = 'Other continents' WHERE `MenuId` = 16042 AND `OptionIndex` = 13;
UPDATE `gossip_menu_option` SET `OptionText` = 'Professional trainer' WHERE `MenuId` = 16042 AND `OptionIndex` = 14;
UPDATE `gossip_menu_option` SET `OptionText` = 'Beast manager' WHERE `MenuId` = 16042 AND `OptionIndex` = 15;
UPDATE `gossip_menu_option` SET `OptionText` = 'Airship controller' WHERE `MenuId` = 16042 AND `OptionIndex` = 16;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of Greenstone Village.' WHERE `MenuId` = 16364 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of Angka Monkey Island.' WHERE `MenuId` = 16364 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me the story of the Tomb of the Forgotten King.' WHERE `MenuId` = 16364 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of the broken army.' WHERE `MenuId` = 16364 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of the brewing storm.' WHERE `MenuId` = 16364 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of the brewing moon festival.' WHERE `MenuId` = 16364 AND `OptionIndex` = 6;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of Theramore\'s fall.' WHERE `MenuId` = 16364 AND `OptionIndex` = 7;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of the attack on Zanivis.' WHERE `MenuId` = 16364 AND `OptionIndex` = 8;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me the story of the dagger in the dark to assassinate Woking.' WHERE `MenuId` = 16364 AND `OptionIndex` = 9;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of Varian and Tyrande in the patience of the king.' WHERE `MenuId` = 16364 AND `OptionIndex` = 10;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of defending the Lion Harbour.' WHERE `MenuId` = 16364 AND `OptionIndex` = 12;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of the fierce battle in the high seas.' WHERE `MenuId` = 16364 AND `OptionIndex` = 13;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the discovery process of Pandaria\'s dark heart.' WHERE `MenuId` = 16364 AND `OptionIndex` = 14;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me the story of the mystery of the angry flame.' WHERE `MenuId` = 16364 AND `OptionIndex` = 15;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the story of Xueshan bloody battle.' WHERE `MenuId` = 16364 AND `OptionIndex` = 16;
UPDATE `gossip_menu_option` SET `OptionText` = 'Enter the trial site.' WHERE `MenuId` = 16811 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to buy something from you.' WHERE `MenuId` = 17051 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see what you have.' WHERE `MenuId` = 18068 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready, Malfurion.' WHERE `MenuId` = 18273 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Illidan asked me to bring this crystal to you.' WHERE `MenuId` = 18273 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I have to be trained.' WHERE `MenuId` = 18380 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I met again, Lin Qi, what\'s new in recent times?' WHERE `MenuId` = 18380 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see your goods.' WHERE `MenuId` = 18383 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to see your favorite jewelry, thank you.' WHERE `MenuId` = 18501 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to buy something from you.' WHERE `MenuId` = 18531 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to see the goods you are selling.' WHERE `MenuId` = 18580 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about the inscription.' WHERE `MenuId` = 18598 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Can I ask you a few questions about this powder?' WHERE `MenuId` = 18598 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'What can you tell me about this powder?' WHERE `MenuId` = 18604 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 18604 AND `OptionIndex` = 7;
UPDATE `gossip_menu_option` SET `OptionText` = 'Can I take your balloon?' WHERE `MenuId` = 18623 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I can teach you enchantment. Are you interested?' WHERE `MenuId` = 18660 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I need an air service.' WHERE `MenuId` = 18723 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Aludane, I have urgent business in Val\'sharah. Can you secure a flight for me?' WHERE `MenuId` = 18723 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Merrill Evil says you will send me to Farona。' WHERE `MenuId` = 18723 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Aludane, I\'m here for the flight to Stormheim.' WHERE `MenuId` = 18723 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready to go to Suramar.' WHERE `MenuId` = 18723 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'I still want to ask...' WHERE `MenuId` = 18727 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to buy something with you.' WHERE `MenuId` = 18728 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'How have you been since Northrend?' WHERE `MenuId` = 18728 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'This alchemy station looks like new.！' WHERE `MenuId` = 18728 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'I have to be trained.' WHERE `MenuId` = 18735 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Sounds really exciting!' WHERE `MenuId` = 18735 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I still want to ask...' WHERE `MenuId` = 18737 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see what tasks you have prepared?' WHERE `MenuId` = 18747 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see the tasks that can be picked up.' WHERE `MenuId` = 18757 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 18758 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see what you have.' WHERE `MenuId` = 18830 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to look at the career advancement options.' WHERE `MenuId` = 18834 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 18845 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to buy something from you.' WHERE `MenuId` = 18913 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 18917 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 18918 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let\'s fight!' WHERE `MenuId` = 18926 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Do you have any plans for both of you?' WHERE `MenuId` = 19035 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Don\'t worry, I have a way.' WHERE `MenuId` = 19045 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to buy something.' WHERE `MenuId` = 19081 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to see the weapons we can choose.' WHERE `MenuId` = 19091 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Again, I want to refresh your memory, Finding the weapons we can do.' WHERE `MenuId` = 19156 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I changed my mind. Let me see which artifacts are available.' WHERE `MenuId` = 19156 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'I changed my mind, I want to choose other artifacts.' WHERE `MenuId` = 19169 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'let us start!' WHERE `MenuId` = 19171 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We are ready to challenge you, Odin!' WHERE `MenuId` = 19198 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about your plan.' WHERE `MenuId` = 19220 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes that use lean legs.' WHERE `MenuId` = 19241 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using wild quail eggs.' WHERE `MenuId` = 19241 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using large pieces of fragrant ribs.' WHERE `MenuId` = 19241 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using fat bear chops.' WHERE `MenuId` = 19241 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using magical blood.' WHERE `MenuId` = 19241 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using the cursed Queen Fish.' WHERE `MenuId` = 19241 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using salmon.' WHERE `MenuId` = 19241 AND `OptionIndex` = 6;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using sorghum squid.' WHERE `MenuId` = 19241 AND `OptionIndex` = 7;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using storm squid.' WHERE `MenuId` = 19241 AND `OptionIndex` = 8;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study the recipes using the scales.' WHERE `MenuId` = 19241 AND `OptionIndex` = 9;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using black barracuda.' WHERE `MenuId` = 19241 AND `OptionIndex` = 10;
UPDATE `gossip_menu_option` SET `OptionText` = 'Study recipes using thick cut bacon.' WHERE `MenuId` = 19241 AND `OptionIndex` = 11;
UPDATE `gossip_menu_option` SET `OptionText` = 'What kind of formula do you sell?' WHERE `MenuId` = 19241 AND `OptionIndex` = 14;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to try the flight challenge, please give me your blessing.' WHERE `MenuId` = 19295 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'How can I complete your trial?' WHERE `MenuId` = 19295 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to know more about you.' WHERE `MenuId` = 19302 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'What happened here?' WHERE `MenuId` = 19302 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about your sword to prevent the resurrection of monsters.' WHERE `MenuId` = 19302 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Ok.' WHERE `MenuId` = 19307 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'It is dead, can it be awakened again?' WHERE `MenuId` = 19308 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Ok.' WHERE `MenuId` = 19309 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Ok.' WHERE `MenuId` = 19310 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = '<Tell Merrill about the information you found.>' WHERE `MenuId` = 19321 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'What is the Guardian Furnace?' WHERE `MenuId` = 19321 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Wait, who are you?' WHERE `MenuId` = 19321 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Can you tell me about Alex again?' WHERE `MenuId` = 19321 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let\'s get out of here!' WHERE `MenuId` = 19331 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 19333 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me participate in your other projects.' WHERE `MenuId` = 19333 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to accept fishing training.' WHERE `MenuId` = 19344 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to buy something from you.' WHERE `MenuId` = 19344 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Have you got a sample of nightmare?' WHERE `MenuId` = 19357 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 19393 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready!' WHERE `MenuId` = 19445 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'As a druid, you know the plants and ingredients used in this food. It is safe and edible.' WHERE `MenuId` = 19457 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 19485 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Haven\'t seen this like...' WHERE `MenuId` = 19513 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Signal to Lilith Moon County.' WHERE `MenuId` = 19515 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'The raven has please.' WHERE `MenuId` = 19540 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = '<Put your emblem on the table.>' WHERE `MenuId` = 19540 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see what you have.' WHERE `MenuId` = 19540 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready to make a decision.' WHERE `MenuId` = 19545 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about your plan.' WHERE `MenuId` = 19547 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about your plan.' WHERE `MenuId` = 19550 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see their story.' WHERE `MenuId` = 19600 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 19601 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see the goods you are selling.' WHERE `MenuId` = 19601 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Anyone looking for a job?' WHERE `MenuId` = 19646 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I need an air service.' WHERE `MenuId` = 19717 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I need to fly to the tomb of Ashaman.' WHERE `MenuId` = 19717 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let\'s get started, I am ready to accept the disguise.' WHERE `MenuId` = 19722 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'anything else?' WHERE `MenuId` = 19741 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'anything else?' WHERE `MenuId` = 19751 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'anything else?' WHERE `MenuId` = 19757 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'anything else?' WHERE `MenuId` = 19761 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Don\'t cover up. I know that you are coming to spy on intelligence for the big magician.' WHERE `MenuId` = 19764 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to enter the private secret store of Dalaran Archmage Alodi.' WHERE `MenuId` = 19778 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I came to ask you about Alex and his ritual. I have to beat Baladur, so I need to get his attention.' WHERE `MenuId` = 19792 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I got the help of Merrill Evil and the spirit of Alody, and we know what to face.' WHERE `MenuId` = 19796 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready to face your demon, the warlock.' WHERE `MenuId` = 19797 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Anyone looking for a job?' WHERE `MenuId` = 19812 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want an eagle to fly to the Marks Camp.' WHERE `MenuId` = 19868 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Is there any rare fishing supplies?' WHERE `MenuId` = 19873 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 19873 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please send me back to Dalaran' WHERE `MenuId` = 19873 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'what do you want to do?' WHERE `MenuId` = 19874 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Then I will go with you.' WHERE `MenuId` = 19875 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Yes, I want to reset the expertise of the artifact.' WHERE `MenuId` = 19948 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Uh do we know each other?' WHERE `MenuId` = 19966 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'What do you sell, Mogos?' WHERE `MenuId` = 19966 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to recruit some followers.' WHERE `MenuId` = 19998 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'The forest is the whole of the common destiny of breathing.' WHERE `MenuId` = 20003 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We are waiting for your order.' WHERE `MenuId` = 20004 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I need your blessing so that I can enter the Emerald Dream.' WHERE `MenuId` = 20015 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'The broken person pays tribute to you.' WHERE `MenuId` = 20018 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We, the Broken, salute you.' WHERE `MenuId` = 20018 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Illidari is always at your service.' WHERE `MenuId` = 20019 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Mimilon, I miss what Hattie used to be. Can you change it back?' WHERE `MenuId` = 20073 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 20094 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to buy something with you.' WHERE `MenuId` = 20157 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let\'s continue research on my artifact.' WHERE `MenuId` = 20176 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Why can\'t I study artifacts?' WHERE `MenuId` = 20176 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let us continue to study my artifacts.' WHERE `MenuId` = 20177 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Why can\'t I study artifacts?' WHERE `MenuId` = 20177 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Do you have prepared artifact survey notes?' WHERE `MenuId` = 20179 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Why can\'t I study artifacts?' WHERE `MenuId` = 20179 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see your goods.' WHERE `MenuId` = 20199 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Release a Warrior Weapons order.' WHERE `MenuId` = 20346 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see what you have.' WHERE `MenuId` = 20356 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see what you have.' WHERE `MenuId` = 20360 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I can help you purchase some precious items.' WHERE `MenuId` = 20405 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Can you tell me about Alex again?' WHERE `MenuId` = 20432 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'What is the mission?' WHERE `MenuId` = 20470 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'let us start.' WHERE `MenuId` = 20470 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see your goods.' WHERE `MenuId` = 20471 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I have heard this story before... <Skip the Legion Reappearance to guide the mission and start your journey from Dalaran.>' WHERE `MenuId` = 20486 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Hey, what?' WHERE `MenuId` = 20492 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'How can I get the magic gold?' WHERE `MenuId` = 20498 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'How to use the magic gold?' WHERE `MenuId` = 20499 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'What happened to your nephew?' WHERE `MenuId` = 20500 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Dalaran sewer' WHERE `MenuId` = 20506 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Illusion' WHERE `MenuId` = 20506 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'bank' WHERE `MenuId` = 20506 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'barber' WHERE `MenuId` = 20506 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Flight manager' WHERE `MenuId` = 20506 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'Guild registrar and guild merchant' WHERE `MenuId` = 20506 AND `OptionIndex` = 6;
UPDATE `gossip_menu_option` SET `OptionText` = 'Hotel' WHERE `MenuId` = 20506 AND `OptionIndex` = 7;
UPDATE `gossip_menu_option` SET `OptionText` = 'mailbox' WHERE `MenuId` = 20506 AND `OptionIndex` = 9;
UPDATE `gossip_menu_option` SET `OptionText` = 'Places of interest' WHERE `MenuId` = 20506 AND `OptionIndex` = 10;
UPDATE `gossip_menu_option` SET `OptionText` = 'Beast manager' WHERE `MenuId` = 20506 AND `OptionIndex` = 11;
UPDATE `gossip_menu_option` SET `OptionText` = 'trainer' WHERE `MenuId` = 20506 AND `OptionIndex` = 12;
UPDATE `gossip_menu_option` SET `OptionText` = 'businessman' WHERE `MenuId` = 20506 AND `OptionIndex` = 13;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to witness again the fall of Illidan Stormrage in the Temple of Darkness, Zela.' WHERE `MenuId` = 20524 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Please let me receive training.' WHERE `MenuId` = 20537 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me where I can fly.' WHERE `MenuId` = 20554 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am looking for the guidance of the guard of the moon.' WHERE `MenuId` = 20603 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'You almost got corrupted by the Burning Legion.' WHERE `MenuId` = 20611 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We will solve this trouble.' WHERE `MenuId` = 20612 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'The Burning Legion will pay for it!' WHERE `MenuId` = 20613 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Transfer to the Tower of the Night.' WHERE `MenuId` = 20697 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to enter my bank.' WHERE `MenuId` = 20724 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to enter my bank.' WHERE `MenuId` = 20725 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to enter my bank.' WHERE `MenuId` = 20726 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I heard that you have prepared a "rental demon?" for me?' WHERE `MenuId` = 20730 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I don\'t like this demon.' WHERE `MenuId` = 20730 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Yes, take me back.' WHERE `MenuId` = 20738 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to learn your blacksmith technique, Kuren.' WHERE `MenuId` = 20749 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Hey, what?' WHERE `MenuId` = 20761 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready to face Leicester. (100 Void Fragments|TINTERFACE\\ICONS\\inv_datacrystal01.blp\n:16|t）' WHERE `MenuId` = 20778 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready to face Kurul. (100 Void Fragments|TINTERFACE\\ICONS\\inv_datacrystal01.blp\n:16|t）' WHERE `MenuId` = 20778 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'Send me to see the movie (free).' WHERE `MenuId` = 20778 AND `OptionIndex` = 9;
UPDATE `gossip_menu_option` SET `OptionText` = 'Send me to see Agatha... (free)' WHERE `MenuId` = 20778 AND `OptionIndex` = 10;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready to face Kurul (free).' WHERE `MenuId` = 20778 AND `OptionIndex` = 13;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see the goods you are selling.' WHERE `MenuId` = 20815 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready! Send me to the door of the brave. [Join Scene Queue]' WHERE `MenuId` = 20835 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'For the glory of the high mountains. I\'m ready! [Join the scene battle queue]' WHERE `MenuId` = 20886 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let us hear what she said, Magni.' WHERE `MenuId` = 20895 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 20896 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'What can we do for you?' WHERE `MenuId` = 20904 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Wake up, Godlin.' WHERE `MenuId` = 20908 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Are we still going?' WHERE `MenuId` = 20985 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready to fight side by side with you.' WHERE `MenuId` = 21004 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Primestone?' WHERE `MenuId` = 21004 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Thunderhorn?' WHERE `MenuId` = 21004 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 21013 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Rumblerock?' WHERE `MenuId` = 21013 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Can you shut up?' WHERE `MenuId` = 21017 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Bronzebeard?' WHERE `MenuId` = 21017 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Ironband?' WHERE `MenuId` = 21017 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Silvervein?' WHERE `MenuId` = 21017 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to see your goods.' WHERE `MenuId` = 21018 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Darkcore?' WHERE `MenuId` = 21018 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Meadowrun?' WHERE `MenuId` = 21018 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Moonstrike?' WHERE `MenuId` = 21018 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Obsidian?' WHERE `MenuId` = 21018 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Snowcrown?' WHERE `MenuId` = 21018 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready, Archbishop.' WHERE `MenuId` = 21049 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We should move on.' WHERE `MenuId` = 21058 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Bellowrage?' WHERE `MenuId` = 21058 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Starglade?' WHERE `MenuId` = 21058 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Skychaser?' WHERE `MenuId` = 21058 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Stormbrow?' WHERE `MenuId` = 21058 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Winterhoof?' WHERE `MenuId` = 21058 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to buy something from you.' WHERE `MenuId` = 21059 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Why does an imaginary spirit travel with a boat\'s draenei?' WHERE `MenuId` = 21059 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Do you know someone who is called a "double leader"?' WHERE `MenuId` = 21059 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Riversong?' WHERE `MenuId` = 21059 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 21072 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Bloodhoof?' WHERE `MenuId` = 21072 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Darkhorn?' WHERE `MenuId` = 21072 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder High Mountain?' WHERE `MenuId` = 21072 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Moonwarden?' WHERE `MenuId` = 21072 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Morningdew?' WHERE `MenuId` = 21072 AND `OptionIndex` = 5;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Wheathoof?' WHERE `MenuId` = 21072 AND `OptionIndex` = 6;
UPDATE `gossip_menu_option` SET `OptionText` = 'Where is Elder Runetotem?' WHERE `MenuId` = 21072 AND `OptionIndex` = 7;
UPDATE `gossip_menu_option` SET `OptionText` = 'I and Aurelia will protect you.' WHERE `MenuId` = 21075 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to use the moonwing owl form.' WHERE `MenuId` = 21079 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I don\'t want to use the moonwing owl form anymore.' WHERE `MenuId` = 21079 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see it.' WHERE `MenuId` = 21144 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.let\'s go!' WHERE `MenuId` = 21161 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We are ready. Let\'s try again!' WHERE `MenuId` = 21161 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Just waiting for you!' WHERE `MenuId` = 21161 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let\'s try again!' WHERE `MenuId` = 21161 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Is there anything strange about it recently?' WHERE `MenuId` = 21164 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Is there anything strange about it recently?' WHERE `MenuId` = 21165 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Is there anything strange about it recently?' WHERE `MenuId` = 21166 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Is there anything strange about it recently?' WHERE `MenuId` = 21167 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'How do the Argent Crusade riders fight?' WHERE `MenuId` = 21167 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I understand, thank you.' WHERE `MenuId` = 21168 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I understand, thank you.' WHERE `MenuId` = 21169 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I understand, thank you.' WHERE `MenuId` = 21170 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Just waiting for you.' WHERE `MenuId` = 21172 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let\'s adjust the tactics.\n|cFF0000FF（Change the talent of Cromi.）|r' WHERE `MenuId` = 21172 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.Let us save your life!\n|cFF0000FF（Start the scene battle.）|r' WHERE `MenuId` = 21172 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to leave here.' WHERE `MenuId` = 21173 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Send me to the Dark Temple (a copy of the time and space roaming team).' WHERE `MenuId` = 21193 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Send me back to Anturus.' WHERE `MenuId` = 21203 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Send me to the surface.' WHERE `MenuId` = 21208 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready to go to the banned prison.' WHERE `MenuId` = 21208 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Open fire!' WHERE `MenuId` = 21208 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready, Rom.' WHERE `MenuId` = 21208 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am ready, Rom.' WHERE `MenuId` = 21208 AND `OptionIndex` = 4;
UPDATE `gossip_menu_option` SET `OptionText` = 'We are looking for someone to attack Cromi. Have you encountered any strange things?' WHERE `MenuId` = 21218 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We can help.' WHERE `MenuId` = 21219 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We are looking for someone to attack Cromi. We heard that you have encountered some trouble with the Magic Net - do you think these two things will be related?' WHERE `MenuId` = 21220 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We can help.' WHERE `MenuId` = 21221 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I wish to unlearn my talents.' WHERE `MenuId` = 21221 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I wish to know about Dual Talent Specialization.' WHERE `MenuId` = 21221 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to fight with you.' WHERE `MenuId` = 21242 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to fight with you.' WHERE `MenuId` = 21243 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to fight with you.' WHERE `MenuId` = 21244 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let\'s get started, Turalyon.' WHERE `MenuId` = 21245 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 21247 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am looking for the enlightenment mark.' WHERE `MenuId` = 21253 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 21282 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Is the trial finished?' WHERE `MenuId` = 21291 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Why are the Boulderfist out this far? You know that this is Kurenai territory.' WHERE `MenuId` = 21291 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Perhaps I can be of some assistance. I will make a deal with you, Satyr. I shall recover this unforged breastplate and slay the beast. In exchange for this task, you will teach me how to create the breastplate' WHERE `MenuId` = 21326 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'let\'s go!' WHERE `MenuId` = 21326 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me see it.' WHERE `MenuId` = 21333 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 21334 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'exhaust vent' WHERE `MenuId` = 21377 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'We are ready.' WHERE `MenuId` = 21383 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'What is behind you?' WHERE `MenuId` = 21451 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'What is the portal doing here?' WHERE `MenuId` = 21454 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Interesting... Why don\'t you wear shoes?' WHERE `MenuId` = 21456 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'But you are sitting here.' WHERE `MenuId` = 21457 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Make this inn your home.' WHERE `MenuId` = 21462 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Nice to meet you, I Shana. Are you ok?' WHERE `MenuId` = 21462 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Let me browse your goods.' WHERE `MenuId` = 21462 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'I understand.' WHERE `MenuId` = 21477 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'What happened to you in the seat of the ruling group?' WHERE `MenuId` = 21478 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'What information do you have, Alleria?' WHERE `MenuId` = 21505 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Turalyon wants to ask about the situation here.' WHERE `MenuId` = 21507 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.I want to see the goods you are selling.' WHERE `MenuId` = 21509 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.I want to see the goods you are selling.' WHERE `MenuId` = 21513 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I am looking for a lost partner.' WHERE `MenuId` = 21580 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'I want to treat and resurrect my fighting pets.' WHERE `MenuId` = 21580 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 21600 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready.' WHERE `MenuId` = 21675 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Burning throne' WHERE `MenuId` = 21687 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'What happened here, the prophet?' WHERE `MenuId` = 21709 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Can you let me see what Silithus was like before the world was traumatized?' WHERE `MenuId` = 21720 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Can you take me back to the present?' WHERE `MenuId` = 21720 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Illidan asked me to bring this crystal to you.' WHERE `MenuId` = 21755 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'exhaust vent' WHERE `MenuId` = 21829 AND `OptionIndex` = 1;
UPDATE `gossip_menu_option` SET `OptionText` = 'Burning throne' WHERE `MenuId` = 21829 AND `OptionIndex` = 2;
UPDATE `gossip_menu_option` SET `OptionText` = 'Dalaran above the broken archipelago' WHERE `MenuId` = 21829 AND `OptionIndex` = 3;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about what happened to the lion\'s sleep.' WHERE `MenuId` = 22009 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Tell me about what happened at the party.' WHERE `MenuId` = 22011 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I\'m ready. Let\'s start the ceremony.' WHERE `MenuId` = 22025 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I need to fly to the Deer Helmet.' WHERE `MenuId` = 22123 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'I must meet with Magni Bronze immediately.' WHERE `MenuId` = 22129 AND `OptionIndex` = 0;
UPDATE `gossip_menu_option` SET `OptionText` = 'Khadgar asked me to send a letter.' WHERE `MenuId` = 22209 AND `OptionIndex` = 0;