-- Quest Objectives Now Appear on Minimap
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Maybell\'s Love Letter (Provided)' WHERE  `ID`=252711;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Gramma Stonefield\'s Note (Provided)' WHERE  `ID`=251774;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Tender Boar Meat (4)' WHERE  `ID`=252189;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Pork Belly Pie (Provided)' WHERE  `ID`=252535;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Garrick\'s Head' WHERE  `ID`=252011;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Nondescript Letter (Provided)' WHERE  `ID`=251886;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Painted Gnoll Armband (8)' WHERE  `ID`=252108;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Red Burlap Bandana (8)' WHERE  `ID`=254809;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Tharil\'zun\'s Head' WHERE  `ID`=251790;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Battleworn Axe (10)' WHERE  `ID`=251825;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Pendant of the Sea Lion' WHERE  `ID`=251730;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Diseased Wolf Pelt (8)' WHERE  `ID`=251702;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Bellygrub\'s Tusk' WHERE  `ID`=252167;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Verna\'s Westfall Stew Recipe (Provided)' WHERE  `ID`=254844;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Torn Murloc Fin (8)' WHERE  `ID`=254717;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Gold Dust (10)' WHERE  `ID`=251758;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Marshal McBride\'s Documents (Provided)' WHERE  `ID`=252181;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Stormwind Armor Marker (Provided)' WHERE  `ID`=254742;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Large Candle (8)' WHERE  `ID`=251686;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='William\'s Shipment (Provided)' WHERE  `ID`=251747;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Furlbrow\'s Pocket Watch' WHERE  `ID`=251838;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='A Dusty Unsent Letter (Provided)' WHERE  `ID`=252275;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='An Undelivered Letter' WHERE  `ID`=251964;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Rolf and Malakai\'s Medallions (Provided)' WHERE  `ID`=252131;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='A Torn Journal Page (Provided)' WHERE  `ID`=251925;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='A Faded Journal Page' WHERE  `ID`=251899;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Hinterlands Honey Ripple (10)' WHERE  `ID`=251941;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='A Faded Journal Page (Provided)' WHERE  `ID`=252527;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Muddy Journal Pages (Provided)' WHERE  `ID`=252032;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Centipaar Insect Parts (5)' WHERE  `ID`=252130;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Linen Scrap (6)' WHERE  `ID`=251970;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Bernice\'s Necklace' WHERE  `ID`=252453;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Brass Collar' WHERE  `ID`=254941;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Iron Pike (5)' WHERE  `ID`=252549;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Iron Rivet (5)' WHERE  `ID`=252550;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Shadowhide Pendant (10)' WHERE  `ID`=252365;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Glyph of Azora (Provided)' WHERE  `ID`=256799;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0',  `Description`='Shard of Water (Provided)' WHERE  `ID`=257052;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Mistmantle Family Ring' WHERE  `ID`=251817;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Pyrewood Shackle (6)' WHERE  `ID`=252462;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Ghoul Fang (10)' WHERE  `ID`=255783;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Vial of Spider Venom (5)' WHERE  `ID`=255784;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Skeleton Finger (10)' WHERE  `ID`=255785;
UPDATE `quest_objectives` SET `Flags`='1', `Flags2`='0', `Description`='Gnoll Paw (8)' WHERE  `ID`=252379;